<?xml version="1.0" encoding="utf-8"?><Database Name="axdb30sp1Kia" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.20.16.24;Initial Catalog=axdb30sp1Kia;User ID=kiaweb" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="axdb30sp1KiaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CUSTTABLE" Member="CUSTTABLEs">
    <Type Name="CUSTTABLE">
      <Column Name="ACCOUNTNUM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TELEFAX" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="INVOICEACCOUNT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CUSTGROUP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LINEDISC" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PAYMTERMID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CASHDISC" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CURRENCY" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BLOCKED" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ONETIMECUSTOMER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCOUNTSTATEMENT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREDITMAX" Type="System.Decimal" DbType="Decimal(28,12) NOT NULL" CanBeNull="false" />
      <Column Name="MANDATORYCREDITLIMIT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DIMENSION" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DIMENSION2_" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DIMENSION3_" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DIMENSION4_" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DIMENSION5_" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="VENDACCOUNT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TELEX" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PRICEGROUP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MULTILINEDISC" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ENDDISC" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="VATNUM" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="COUNTRY" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="INVENTLOCATION" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DLVTERM" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DLVMODE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MARKUPGROUP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CLEARINGPERIOD" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ZIPCODE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="STATE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="COUNTY" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="CELLULARPHONE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PHONELOCAL" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FREIGHTZONE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CREDITRATING" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TAXGROUP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="STATISTICSGROUP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PAYMMODE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BANKACCOUNT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NAMEALIAS" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CONTACTPERSONID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="INVOICEADDRESS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OURACCOUNTNUM" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SALESPOOLID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DEL_QUOTATIONCOPIES" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEL_QUOTATIONORIGINALS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEL_CONFIRMATIONORIGINALS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEL_INVOICECOPIES" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEL_INVOICEORIGINALS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEL_PACKINGSLIPCOPIES" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEL_PACKINGSLIPORIGINALS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEL_CONFIRMATIONCOPIES" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="INCLTAX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUSTITEMGROUPID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NUMBERSEQUENCEGROUP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LANGUAGEID" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PAYMDAYID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LINEOFBUSINESSID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DESTINATIONCODEID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GIROTYPE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUPPITEMGROUPID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GIROTYPEINTERESTNOTE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TAXLICENSENUM" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="WEBSALESORDERDISPLAY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PAYMSPEC" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BANKCENTRALBANKPURPOSETEXT" Type="System.String" DbType="VarChar(140) NOT NULL" CanBeNull="false" />
      <Column Name="BANKCENTRALBANKPURPOSECODE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PRINTMODULETYPE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CITY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STREET" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PAGER" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SMS" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="REFZIPCODE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PACKMATERIALFEELICENSENUM" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PHONECOMPANY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NEL_XALDATAID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NEL_XALFILEID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NEL_XALRECID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CARACCOUNT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NELDEALER" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CLAIMOK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="INTFREETXT" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="EXTFREETXT" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="SALESEXTINT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DEALER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JDDEALERNO" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FAGGRUPPE" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CLAIMCUSTOMER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JDDEALERCCE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE2" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CELLULARPHONE2" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PRICEGROUPCLAIM" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TIMEPRISREKL" Type="System.Decimal" DbType="Decimal(28,12) NOT NULL" CanBeNull="false" />
      <Column Name="NETTOPCTREKL" Type="System.Decimal" DbType="Decimal(28,12) NOT NULL" CanBeNull="false" />
      <Column Name="NELCOSTLEDGERACCOUNT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HIDEMENULINES" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NELSTREETNAME2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NELNAME2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NELDATAAREAID" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="NELCUSTACCOUNT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CONSCUSTYESNO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CONSACCOUNT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NELENVIRONMENTCODE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NELKIA_DEALERCODEDCS" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NELKIA_DEALERACTIVE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NELNEXTCLAIMNO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NELLASTCLAIMUSER" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NELLASTCLAIMDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NELCLAIMREPHOURPRICE" Type="System.Decimal" DbType="Decimal(28,12) NOT NULL" CanBeNull="false" />
      <Column Name="NELCLAIMREPHOURPRICEDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NELCLAIMHANDLINGCHARGE" Type="System.Decimal" DbType="Decimal(28,12) NOT NULL" CanBeNull="false" />
      <Column Name="NELKIA_VIC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NELKIA_CLAIMDATEFROM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NELKIA_CLAIMDATETO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NELKIA_CONTRACTDATEFROM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NELKIA_CONTRACTDATETO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIEDDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIEDTIME" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIEDBY" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CREATEDDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CREATEDTIME" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATEDBY" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DATAAREAID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RECID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NELKIA_PAINTSHOP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NELJYSKEFINANS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DMSCUSTREKVISITIONYESNO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MSA_PDF" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MSA_PDFRECIEVETYPE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NELKIA_DEALERTYPE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NELCLAIMREPHOURPRICEFACTORYCUR" Type="System.Decimal" DbType="Decimal(28,12) NOT NULL" CanBeNull="false" />
      <Column Name="NELCLAIMREPHOURFACTORYCURRENCY" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NELWPERSON" Member="NELWPERSONs">
    <Type Name="NELWPERSON">
      <Column Name="BRUGERKODE" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ADGANGSKODE" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MEDARBEJDERNAVN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DEALERACCOUNT" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="TELEFON" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BRUGERSTATUS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LASTLOGIN" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RETTSALES" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTPARTS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTTECHNIC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTVIN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTSUPERVISOR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTCLAIM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTDELREPORT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTINTERN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTMARKETING" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTGENERAL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTSERVICE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTBOOKING" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIEDDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIEDTIME" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MODIFIEDBY" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CREATEDDATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CREATEDTIME" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATEDBY" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DATAAREAID" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RECID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTFACTORY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RETTKID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COODEALERID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CUSTACCOUNT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="RETTBM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COLOURCARBOOKING" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>